In [24]:
# what is fst 
# fst -  finite state transducer 
# "any stem + छु" → "any stem + <SLOT>छु"
# it splits root and suffix 
# this works for  every verb ending in छु -->.गर्छु, खान्छु, जान्छु,
#  गर्छु --FST runs ---> गर्  +  <SLOT>  +  छु

In [25]:
# approach 
# extract suffix rules from paradigm.csv
# Build FST using those rules

In [26]:
import pandas as pd 

df = pd.read_csv('../data/paradigm.csv')
df

      stem stem_nepali          slot surface_form              gloss verified
0      gar         गर्      1SG.PRES        गर्छु               I do      YES
1      gar         गर्      2SG.PRES       गर्छस्  you do (informal)      YES
2      gar         गर्  2SG.PRES.MID        गर्छौ  you do (friendly)      YES
3      gar         गर्      3SG.PRES         गर्छ        he/she does      YES
4      gar         गर्      1PL.PRES       गर्छौं              we do      YES
..     ...         ...           ...          ...                ...      ...
145  sahar         सहर           ACC       सहरलाई      city (object)      YES
146  sahar         सहर           GEN        सहरको        of the city      YES
147  sahar         सहर           LOC        सहरमा     in/at the city      YES
148  sahar         सहर           ABL       सहरबाट      from the city      YES
149  sahar         सहर           INS        सहरले        by the city      YES

[150 rows x 6 columns]

In [27]:
df[['slot','surface_form','stem_nepali']]

             slot surface_form stem_nepali
0        1SG.PRES        गर्छु         गर्
1        2SG.PRES       गर्छस्         गर्
2    2SG.PRES.MID        गर्छौ         गर्
3        3SG.PRES         गर्छ         गर्
4        1PL.PRES       गर्छौं         गर्
..            ...          ...         ...
145           ACC       सहरलाई         सहर
146           GEN        सहरको         सहर
147           LOC        सहरमा         सहर
148           ABL       सहरबाट         सहर
149           INS        सहरले         सहर

[150 rows x 3 columns]

In [35]:
def extract_suffix(stem, surface_form):
    if surface_form.startswith(stem):
        return surface_form[len(stem):]
    else:
        return None

df['suffix'] = df.apply(
    lambda row: extract_suffix(row['stem_nepali'], row['surface_form']),axis=1)

df

,stem,stem_nepali,slot,surface_form,gloss,verified,suffix
0,gar,गर्,1SG.PRES,गर्छु,I do,YES,छु
1,gar,गर्,2SG.PRES,गर्छस्,you do (informal),YES,छस्
2,gar,गर्,2SG.PRES.MID,गर्छौ,you do (friendly),YES,छौ
3,gar,गर्,3SG.PRES,गर्छ,he/she does,YES,छ
4,gar,गर्,1PL.PRES,गर्छौं,we do,YES,छौं
...,...,...,...,...,...,...,...
145,sahar,सहर,ACC,सहरलाई,city (object),YES,लाई
146,sahar,सहर,GEN,सहरको,of the city,YES,को
147,sahar,सहर,LOC,सहरमा,in/at the city,YES,मा
148,sahar,सहर,ABL,सहरबाट,from the city,YES,बाट
149,sahar,सहर,INS,सहरले,by the city,YES,ले

'गर्'